name: build
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          os: [windows-2019, windows-2016]
          architecture: [x64, x86]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: powershell ./.github/workflows/build.ps1 ${{matrix.architecture}} vs16
      - uses: actions/upload-artifact@v2
        with:
          name: libsodium-test-vs16-${{matrix.architecture}}
          path: ./winlibs/
