name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: powershell ./.github/workflows/build.ps1
      - run: tree /f /a $Env:GITHUB_WORKSPACE\winlibs
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./winlibs/libsodium-test-vs16-x64.zip
